plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

base {
    archivesName = "${project.mod_id}-fabric"
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft_version}:${parchment_mappings_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    // Create slim jar for compile-time mixin resolution
    modCompileOnly("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") {
        transitive = false
    }
    modCompileOnly("net.createmod.ponder:Ponder-Fabric-${minecraft_version}:1.0.91") {
        transitive = false
    }
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath = aw
    }

    mixin {
        defaultRefmapName = "${mod_id}.refmap.json"
    }

    runs {
        client {
            client()
            runDir 'runs/client'
            ideConfigGenerated true
        }
        server {
            server()
            runDir 'runs/server'
            ideConfigGenerated true
        }
    }
}
