org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

version=1.0.0+1.21.1
minecraft_version=1.21.1

additional_minecraft_versions=
minimum_minecraft_version=1.21.1

branch=main
group=com.uberswe.createschematicdownload
mod_name=CreateSchematicDownload
mod_id=createschematicdownload
enabled_platforms=neoforge

systemProp.javax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl
systemProp.javax.xml.transform.TransformerFactory=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl
systemProp.javax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
