plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
}

base {
    archivesName = "${project.mod_id}-forge"
}

legacyForge {
    version = "1.20.1-${project.forge_version}"

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
        }

        server {
            server()
            programArgument '--nogui'
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    modCompileOnly("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") {
        transitive = false
    }
    modCompileOnly("net.createmod.ponder:Ponder-Forge-${minecraft_version}:1.0.91") {
        transitive = false
    }
    compileOnly("io.github.llamalad7:mixinextras-common:0.4.1")
}

jar {
    manifest.attributes(
        'MixinConfigs': 'createschematichelper.mixins.json,createschematichelper.forge.mixins.json'
    )
}

// Generate mod metadata from templates
var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
        minecraft_version      : minecraft_version,
        minecraft_version_range: minecraft_version_range,
        forge_version          : forge_version,
        forge_version_range    : forge_version_range,
        forge_loader_version_range: forge_loader_version_range,
        mod_id                 : mod_id,
        mod_name               : mod_name,
        mod_license            : mod_license,
        mod_version            : mod_version,
        mod_authors            : mod_authors,
        mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
legacyForge.ideSyncTask generateModMetadata
