plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = project.neo_form_version

    parchment {
        mappingsVersion = project.parchment_neoforge_mappings_version
        minecraftVersion = project.parchment_neoforge_minecraft_version
    }
}

dependencies {
    compileOnly("org.spongepowered:mixin:0.8.7")
    compileOnly("io.github.llamalad7:mixinextras-common:0.4.1")
    annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1")

    compileOnly("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") {
        transitive = false
    }
}
