plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev.legacyforge'
}

legacyForge {
    mcpVersion = "1.20.1"

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }
}

dependencies {
    compileOnly("org.spongepowered:mixin:0.8.5")

    compileOnly("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") {
        transitive = false
    }
}
