plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

base {
    archivesName = "${project.mod_id}-neoforge-mc${project.minecraft_version}"
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_neoforge_mappings_version
        minecraftVersion = project.parchment_neoforge_minecraft_version
    }

    runs {
        client {
            client()
        }

        server {
            server()
            programArgument '--nogui'
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    compileOnly("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") {
        transitive = false
    }
    compileOnly("net.createmod.ponder:ponder-neoforge:1.0.81+mc${minecraft_version}")
}

// Generate mod metadata from templates
var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
        minecraft_version      : minecraft_version,
        minecraft_version_range: minecraft_version_range,
        neo_version            : neo_version,
        neo_version_range      : neo_version_range,
        loader_version_range   : loader_version_range,
        mod_id                 : mod_id,
        mod_name               : mod_name,
        mod_license            : mod_license,
        mod_version            : mod_version,
        mod_authors            : mod_authors,
        mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata
